### ISSUE TITLE
Append new rki sms data to file results/010_rki_sms_eingangsdatum_cumpos_cumdead.txt

### ISSUE THREAD

**Issue by holgerman** [holgerman/covid19regional#1]
Use output from  010_datint_scrape_websites_sms_rki_20-05-10.R to append 
results/010_rki_sms_eingangsdatum_cumpos_cumdead.txt

**Comment by knenovsky** [comment]
results/010_rki_sms_eingangsdatum_cumpos_cumdead.txt will contain the newest data
